suite: config template | cache config
release:
  name: gitea-unittests
  namespace: testing
tests:
  - it: "cache is configured correctly for redis-cluster"
    template: templates/gitea/config.yaml
    set:
      redis-cluster:
        enabled: true
    asserts:
      - documentIndex: 0
        equal:
          path: stringData.cache
          value: |-
            ADAPTER=redis
            HOST=redis+cluster://:@gitea-unittests-redis-cluster-headless.testing.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s&

  - it: "cache is configured correctly for 'memory' when redis-cluster is disabled"
    template: templates/gitea/config.yaml
    set:
      redis-cluster:
        enabled: false
    asserts:
      - documentIndex: 0
        equal:
          path: stringData.cache
          value: |-
            ADAPTER=memory
            HOST=

  - it: "cache can be customized when redis-cluster is disabled"
    template: templates/gitea/config.yaml
    set:
      redis-cluster:
        enabled: false
      gitea.config.cache.ADAPTER: custom-adapter
      gitea.config.cache.HOST: custom-host
    asserts:
      - documentIndex: 0
        equal:
          path: stringData.cache
          value: |-
            ADAPTER=custom-adapter
            HOST=custom-host
